package com.j2ee.project.entities;
// Generated Jun 1, 2017 7:35:56 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Authority generated by hbm2java
 */
@Entity
@Table(name = "authority", catalog = "bookstore_renting")
public class Authority implements java.io.Serializable {

	private Integer id;
	private String username;
	private String userRole;

	public Authority() {
	}

	public Authority(String username, String userRole) {
		this.username = username;
		this.userRole = userRole;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "user_role", nullable = false, length = 50)
	public String getUserRole() {
		return this.userRole;
	}

	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

}
