package com.j2ee.project.entities;
// Generated May 13, 2017 8:58:41 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonView;
import com.j2ee.project.entities.search.Views;

/**
 * Sach generated by hbm2java
 */
@Entity
@Table(name = "sach", catalog = "bookstore_renting")
public class Sach implements java.io.Serializable {

	private Integer id;
	
	@JsonView(Views.Show.class)
	private String maSach;
	
	@JsonView(Views.Show.class)
	private String ten;
	
	@JsonView(Views.Show.class)
	private String tomTat;
	
	private Integer soBan;
	
	private Date ngayTao;
	
	@JsonView(Views.Show.class)
	private String ghiChu;
	
	@JsonView(Views.Show.class)
	private String imageUrl;

	public Sach() {
	}

	public Sach(String maSach, String ten, String tomTat, Integer soBan, Date ngayTao, String ghiChu, String imageUrl) {
		this.maSach = maSach;
		this.ten = ten;
		this.tomTat = tomTat;
		this.soBan = soBan;
		this.ngayTao = ngayTao;
		this.ghiChu = ghiChu;
		this.imageUrl = imageUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "MaSach", length = 12)
	public String getMaSach() {
		return this.maSach;
	}

	public void setMaSach(String maSach) {
		this.maSach = maSach;
	}

	@Column(name = "Ten", length = 500)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Column(name = "TomTat", length = 1000)
	public String getTomTat() {
		return this.tomTat;
	}

	public void setTomTat(String tomTat) {
		this.tomTat = tomTat;
	}

	@Column(name = "SoBan")
	public Integer getSoBan() {
		return this.soBan;
	}

	public void setSoBan(Integer soBan) {
		this.soBan = soBan;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NgayTao", length = 19)
	public Date getNgayTao() {
		return this.ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		this.ngayTao = ngayTao;
	}

	@Column(name = "GhiChu", length = 2000)
	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

	@Column(name = "ImageUrl", length = 1000)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

}
