package com.j2ee.project.entities;
// Generated Jun 1, 2017 7:35:56 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Thongtinmuonsach generated by hbm2java
 */
@Entity
@Table(name = "thongtinmuonsach", catalog = "bookstore_renting")
public class Thongtinmuonsach implements java.io.Serializable {

	private Integer id;
	private String tenDocGia;
	private String diaChi;
	private String soDienThoai;
	private Date ngayTao;
	private String ghiChu;

	public Thongtinmuonsach() {
	}

	public Thongtinmuonsach(String tenDocGia, String diaChi, String soDienThoai, Date ngayTao, String ghiChu) {
		this.tenDocGia = tenDocGia;
		this.diaChi = diaChi;
		this.soDienThoai = soDienThoai;
		this.ngayTao = ngayTao;
		this.ghiChu = ghiChu;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "TenDocGia", length = 50)
	public String getTenDocGia() {
		return this.tenDocGia;
	}

	public void setTenDocGia(String tenDocGia) {
		this.tenDocGia = tenDocGia;
	}

	@Column(name = "DiaChi", length = 500)
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "SoDienThoai", length = 20)
	public String getSoDienThoai() {
		return this.soDienThoai;
	}

	public void setSoDienThoai(String soDienThoai) {
		this.soDienThoai = soDienThoai;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NgayTao", length = 19)
	public Date getNgayTao() {
		return this.ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		this.ngayTao = ngayTao;
	}

	@Column(name = "GhiChu", length = 2000)
	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

}
